sudo: required

services:
  - docker

before_install:
  - chmod +x build.sh
  - chmod +x dist.sh

jobs:
  include:
    - stage: Build Docker Images
      script:
        - $TRAVIS_BUILD_DIR/build.sh
    - stage: Deploys Docker Images to Docker Hub
      if: type != pull_request AND (branch = master OR tag IS present)
      script:
        - $TRAVIS_BUILD_DIR/dist.sh
